/**
 * Combine and render mode tables of the gfx_tev tests, shared by the host test (test_tev.c) and the Dolphin
 * test DOL (dol_tev.c). Include after gfx_internal.h and rdp_model.h.
 */
#ifndef GFX_TEV_CASES_H
#define GFX_TEV_CASES_H

typedef struct {
    const char* name;
    uint32_t hi, lo;
    uint32_t cycle;
    GfxPrimKind kind;
    uint32_t geom;
} CombCase;

#define TRI (G_ZBUFFER | G_SHADE | G_SHADING_SMOOTH)

static const CombCase sCombCases[] = {
    /* 1-cycle (the second cycle's settings are the ones the RDP uses) */
    { "PRIMITIVE", MODE(G_CC_PRIMITIVE, G_CC_PRIMITIVE), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "SHADE", MODE(G_CC_SHADE, G_CC_SHADE), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "MODULATEI", MODE(G_CC_MODULATEI, G_CC_MODULATEI), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "MODULATEIA", MODE(G_CC_MODULATEIA, G_CC_MODULATEIA), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "MODULATEIDECALA", MODE(G_CC_MODULATEIDECALA, G_CC_MODULATEIDECALA), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "MODULATEI_PRIM", MODE(G_CC_MODULATEI_PRIM, G_CC_MODULATEI_PRIM), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "MODULATEIA_PRIM rect", MODE(G_CC_MODULATEIA_PRIM, G_CC_MODULATEIA_PRIM), G_CYC_1CYCLE, GFX_PRIM_TEXRECT, 0 },
    { "MODULATEIDECALA_PRIM", MODE(G_CC_MODULATEIDECALA_PRIM, G_CC_MODULATEIDECALA_PRIM), G_CYC_1CYCLE,
      GFX_PRIM_TRIANGLE, TRI },
    { "DECALRGB", MODE(G_CC_DECALRGB, G_CC_DECALRGB), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "DECALRGBA rect", MODE(G_CC_DECALRGBA, G_CC_DECALRGBA), G_CYC_1CYCLE, GFX_PRIM_TEXRECT, 0 },
    { "BLENDI", MODE(G_CC_BLENDI, G_CC_BLENDI), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "BLENDIA", MODE(G_CC_BLENDIA, G_CC_BLENDIA), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "BLENDRGBA", MODE(G_CC_BLENDRGBA, G_CC_BLENDRGBA), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "ADDRGB", MODE(G_CC_ADDRGB, G_CC_ADDRGB), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "REFLECTRGB", MODE(G_CC_REFLECTRGB, G_CC_REFLECTRGB), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "HILITERGBA", MODE(G_CC_HILITERGBA, G_CC_HILITERGBA), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "SHADEDECALA", MODE(G_CC_SHADEDECALA, G_CC_SHADEDECALA), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "BLENDPE rect", MODE(G_CC_BLENDPE, G_CC_BLENDPE), G_CYC_1CYCLE, GFX_PRIM_TEXRECT, 0 },
    { "BLENDPEDECALA", MODE(G_CC_BLENDPEDECALA, G_CC_BLENDPEDECALA), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "(T0-K4)*P+S", LERP(0, 0, 0, 0, 0, 0, 0, 0, TEXEL0, K4, PRIMITIVE, SHADE, 0, 0, 0, SHADE), G_CYC_1CYCLE,
      GFX_PRIM_TRIANGLE, TRI },
    { "T0*K5+S", LERP(0, 0, 0, 0, 0, 0, 0, 0, TEXEL0, 0, K5, SHADE, 0, 0, 0, SHADE), G_CYC_1CYCLE, GFX_PRIM_TRIANGLE,
      TRI },
    { "TEXEL1 in 1-cycle", LERP(0, 0, 0, 0, 0, 0, 0, 0, TEXEL1, 0, SHADE, 0, TEXEL1, 0, SHADE, 0), G_CYC_1CYCLE,
      GFX_PRIM_TRIANGLE, TRI },
    { "(T0-P)*EnvA+S generic", LERP(0, 0, 0, 0, 0, 0, 0, 0, TEXEL0, PRIMITIVE, ENV_ALPHA, SHADE, TEXEL0, PRIMITIVE,
                                   ENVIRONMENT, SHADE),
      G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "(1-T0)*P+E", LERP(0, 0, 0, 0, 0, 0, 0, 0, 1, TEXEL0, PRIMITIVE, ENVIRONMENT, 1, TEXEL0, PRIMITIVE, ENVIRONMENT),
      G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "(T0-CENTER)*P+E, alpha (T0-1)*P+E", LERP(0, 0, 0, 0, 0, 0, 0, 0, TEXEL0, 1, PRIMITIVE, ENVIRONMENT, TEXEL0, 1, PRIMITIVE, ENVIRONMENT),
      G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "(0-S)*P+T0", LERP(0, 0, 0, 0, 0, 0, 0, 0, 0, SHADE, PRIMITIVE, TEXEL0, 0, SHADE, PRIMITIVE, TEXEL0),
      G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "PRIM_LOD_FRAC alpha", LERP(0, 0, 0, 0, 0, 0, 0, 0, TEXEL0, 0, PRIM_LOD_FRAC, 0, TEXEL0, 0, PRIM_LOD_FRAC, 0),
      G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "1*PRIM_LOD_FRAC alpha", LERP(0, 0, 0, 0, 0, 0, 0, 0, TEXEL0, 0, SHADE, 0, 1, 0, PRIM_LOD_FRAC, ENVIRONMENT),
      G_CYC_1CYCLE, GFX_PRIM_TRIANGLE, TRI },
    /* 2-cycle */
    { "MODULATEIDECALA, PASS2", MODE(G_CC_MODULATEIDECALA, G_CC_PASS2), G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "MODULATEIDECALA, MODULATEIA_PRIM2", MODE(G_CC_MODULATEIDECALA, G_CC_MODULATEIA_PRIM2), G_CYC_2CYCLE,
      GFX_PRIM_TRIANGLE, TRI },
    { "MODULATEIA_PRIM, PASS2 rect", MODE(G_CC_MODULATEIA_PRIM, G_CC_PASS2), G_CYC_2CYCLE, GFX_PRIM_TEXRECT, 0 },
    { "MODULATEIA, MODULATEIA2", MODE(G_CC_MODULATEIA, G_CC_MODULATEIA2), G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "scene: T0*S, P*C / T0", LERP(TEXEL0, 0, SHADE, 0, 0, 0, 0, TEXEL0, PRIMITIVE, 0, COMBINED, 0, 0, 0, 0, COMBINED),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "scene: T0*S, P*C / C*E", LERP(TEXEL0, 0, SHADE, 0, 0, 0, 0, TEXEL0, PRIMITIVE, 0, COMBINED, 0, COMBINED, 0,
                                    ENVIRONMENT, 0),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "T0*S / 1, C*P", LERP(TEXEL0, 0, SHADE, 0, 0, 0, 0, 1, COMBINED, 0, PRIMITIVE, 0, 0, 0, 0, COMBINED), G_CYC_2CYCLE,
      GFX_PRIM_TRIANGLE, TRI },
    { "TEMPLERP, MODULATEIA_PRIM2", MODE(G_CC_TEMPLERP, G_CC_MODULATEIA_PRIM2), G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "TEMPLERP, MODULATEIA2", MODE(G_CC_TEMPLERP, G_CC_MODULATEIA2), G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "TRILERP (LOD 0), PASS2", MODE(G_CC_TRILERP, G_CC_PASS2), G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "lerp(T0,T1,EnvA) / 1, C*S", LERP(TEXEL1, TEXEL0, ENV_ALPHA, TEXEL0, 0, 0, 0, 1, COMBINED, 0, SHADE, 0, 0, 0, 0,
                                       COMBINED),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "T1*T0 / C*S, C*P", LERP(TEXEL1, 0, TEXEL0, 0, TEXEL0, 0, TEXEL0, 0, COMBINED, 0, SHADE, 0, COMBINED, 0,
                               PRIMITIVE, 0),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "INTERFERENCE, PASS2", MODE(G_CC_INTERFERENCE, G_CC_PASS2), G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "N64 logo text (rect)", LERP(TEXEL1, PRIMITIVE, ENV_ALPHA, TEXEL0, 0, 0, 0, TEXEL0, PRIMITIVE, ENVIRONMENT,
                                   COMBINED, ENVIRONMENT, COMBINED, 0, PRIMITIVE, 0),
      G_CYC_2CYCLE, GFX_PRIM_TEXRECT, 0 },
    { "SETUPDL_0 BLENDPE / PASS", LERP(PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, PRIMITIVE, 0, TEXEL0, 0, 0, 0, 0,
                                       COMBINED, 0, 0, 0, COMBINED),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "SETUPDL_33 hilite", LERP(TEXEL0, 0, PRIMITIVE, SHADE, 1, 0, TEXEL0, SHADE, ENVIRONMENT, COMBINED, TEXEL0,
                                COMBINED, ENVIRONMENT, COMBINED, TEXEL0, COMBINED),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "SETUPDL_40 two textures", LERP(TEXEL1, TEXEL0, PRIMITIVE_ALPHA, TEXEL0, TEXEL1, TEXEL0, PRIMITIVE, TEXEL0, 0,
                                      0, 0, COMBINED, 0, 0, 0, COMBINED),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, G_SHADE },
    { "TEXEL0 in cycle 1: (1-C)*T0+C", LERP(TEXEL0, 0, SHADE, 0, 0, 0, 0, 1, 1, COMBINED, TEXEL0, COMBINED, 0, 0, 0,
                                            COMBINED),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "SETUPDL_29 NOISE", LERP(TEXEL0, 0, SHADE, 0, TEXEL0, 0, SHADE, 0, NOISE, 0, COMBINED, 0, 0, 0, 0, COMBINED),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "DECALRGBA2 (COMBINED_ALPHA)", MODE(G_CC_MODULATEIA, G_CC_DECALRGBA2), G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "HILITERGBA2", MODE(G_CC_MODULATEIA_PRIM, G_CC_HILITERGBA2), G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "cycle 1 two-stage reading COMBINED", LERP(TEXEL0, 0, SHADE, 0, TEXEL0, 0, SHADE, 0, PRIMITIVE, COMBINED,
                                                 ENV_ALPHA, SHADE, PRIMITIVE, COMBINED, ENVIRONMENT, SHADE),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "both cycles two-stage + 2 textures", LERP(TEXEL1, PRIMITIVE, ENV_ALPHA, TEXEL0, TEXEL1, PRIMITIVE, ENVIRONMENT,
                                                 TEXEL0, ENVIRONMENT, COMBINED, SHADE_ALPHA, TEXEL0, SHADE, COMBINED,
                                                 PRIMITIVE, TEXEL0),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "cycle 1 (P-E)*COMBINED+S: saves cycle 0", LERP(TEXEL0, 0, SHADE, 0, TEXEL0, 0, SHADE, 0, PRIMITIVE, ENVIRONMENT,
                                                      COMBINED, SHADE, 0, 0, 0, COMBINED),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "cycle 1 C*Calpha + 2-stage alpha: saves alpha", LERP(TEXEL0, 0, SHADE, 0, TEXEL0, 0, SHADE, 0, COMBINED, 0,
                                                            COMBINED_ALPHA, 0, TEXEL0, PRIMITIVE, ENVIRONMENT, SHADE),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "no shade (G_SHADE off)", MODE(G_CC_MODULATEIA, G_CC_MODULATEIA2), G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, G_ZBUFFER },
    /* Cycle 1 color is a plain COMBINED_ALPHA: it must not be written by the stage that computes cycle 0's
     * alpha (a TEV stage reads TEVPREV before it writes it) */
    { "cycle 1 color = COMBINED_ALPHA", LERP(TEXEL0, 0, SHADE, 0, TEXEL0, 0, SHADE, 0, 1, 0, COMBINED_ALPHA, 0, 0, 0,
                                             0, COMBINED),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
    { "cycle 1 color = COMBINED_ALPHA, alpha 2-stage", LERP(TEXEL0, 0, SHADE, 0, TEXEL0, 0, SHADE, 0, 1, 0,
                                                            COMBINED_ALPHA, 0, PRIMITIVE, COMBINED, ENVIRONMENT, SHADE),
      G_CYC_2CYCLE, GFX_PRIM_TRIANGLE, TRI },
};

typedef struct {
    const char* name;
    uint32_t modeL1, modeL2; /* render mode for 1-cycle, 2-cycle */
    bool checkAlpha;         /* program outputs the final alpha */
    int tol;
} ModeVariant;

static const ModeVariant sModeVariants[] = {
    { "opaque", RM1(OPA_SURF), G_RM_PASS | RM_OPA_SURF(2), false, 4 },
    { "xlu", RM1(XLU_SURF), G_RM_PASS | RM_XLU_SURF(2), true, 4 },
};


typedef struct {
    const char* name;
    uint32_t hi, lo;
    uint32_t cycle, modeL;
    GfxPrimKind kind;
    uint32_t geom;
    bool checkAlpha;
} BlendCase;

static const BlendCase sBlendCases[] = {
    { "FOG_SHADE_A + AA_ZB_OPA_SURF2", MODE(G_CC_MODULATEIDECALA, G_CC_MODULATEIA_PRIM2), G_CYC_2CYCLE,
      G_RM_FOG_SHADE_A | RM_AA_ZB_OPA_SURF(2), GFX_PRIM_TRIANGLE, TRI | G_FOG, false },
    { "FOG_SHADE_A + AA_ZB_XLU_SURF2", MODE(G_CC_MODULATEIA_PRIM, G_CC_MODULATEIA_PRIM2), G_CYC_2CYCLE,
      G_RM_FOG_SHADE_A | RM_AA_ZB_XLU_SURF(2), GFX_PRIM_TRIANGLE, TRI | G_FOG, true },
    { "FOG_SHADE_A + AA_ZB_TEX_EDGE2", MODE(G_CC_MODULATEIA, G_CC_PASS2), G_CYC_2CYCLE,
      G_RM_FOG_SHADE_A | RM_AA_ZB_TEX_EDGE(2), GFX_PRIM_TRIANGLE, TRI | G_FOG, false },
    { "FOG_SHADE_A + ZB_CLD_SURF2 (SETUPDL_0)", LERP(PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, PRIMITIVE, 0, TEXEL0,
                                                     0, 0, 0, 0, COMBINED, 0, 0, 0, COMBINED),
      G_CYC_2CYCLE, G_RM_FOG_SHADE_A | RM_ZB_CLD_SURF(2), GFX_PRIM_TRIANGLE, TRI | G_FOG, true },
    { "FOG_SHADE_A rect (no shade: no fog)", MODE(G_CC_MODULATEIA_PRIM, G_CC_PASS2), G_CYC_2CYCLE,
      G_RM_FOG_SHADE_A | RM_AA_ZB_XLU_SURF(2), GFX_PRIM_TEXRECT, 0, true },
    { "FOG_PRIM_A + AA_ZB_OPA_SURF2 (K3)", MODE(G_CC_MODULATEIA, G_CC_PASS2), G_CYC_2CYCLE,
      G_RM_FOG_PRIM_A | RM_AA_ZB_OPA_SURF(2), GFX_PRIM_TRIANGLE, TRI, false },
    { "FOG_PRIM_A + XLU_SURF2 (K3)", MODE(G_CC_MODULATEIA, G_CC_PASS2), G_CYC_2CYCLE, G_RM_FOG_PRIM_A | RM_XLU_SURF(2),
      GFX_PRIM_TRIANGLE, TRI, true },
    { "AA_ZB_TEX_EDGE 1-cycle", MODE(G_CC_MODULATEIA, G_CC_MODULATEIA), G_CYC_1CYCLE, RM1(AA_ZB_TEX_EDGE),
      GFX_PRIM_TRIANGLE, TRI, false },
    { "TEX_EDGE rect", MODE(G_CC_DECALRGBA, G_CC_DECALRGBA), G_CYC_1CYCLE, RM1(TEX_EDGE), GFX_PRIM_TEXRECT, 0, false },
    { "AA_ZB_XLU_SURF 1-cycle", MODE(G_CC_MODULATEIA, G_CC_MODULATEIA), G_CYC_1CYCLE, RM1(AA_ZB_XLU_SURF),
      GFX_PRIM_TRIANGLE, TRI, true },
    { "CLD_SURF 1-cycle rect", MODE(G_CC_MODULATEIA_PRIM, G_CC_MODULATEIA_PRIM), G_CYC_1CYCLE, RM1(CLD_SURF),
      GFX_PRIM_TEXRECT, 0, true },
    { "ADD (fog alpha)", MODE(G_CC_MODULATEIA, G_CC_MODULATEIA), G_CYC_1CYCLE, RM1(ADD), GFX_PRIM_TRIANGLE, TRI, false },
    { "VISCVG (blend color)", MODE(G_CC_SHADE, G_CC_SHADE), G_CYC_1CYCLE, RM1(VISCVG), GFX_PRIM_TRIANGLE, TRI, false },
    { "NOOP", MODE(G_CC_SHADE, G_CC_SHADE), G_CYC_1CYCLE, RM1(NOOP), GFX_PRIM_TRIANGLE, TRI, false },
    { "threshold + XLU_SURF 1-cycle", MODE(G_CC_MODULATEIA_PRIM, G_CC_MODULATEIA_PRIM), G_CYC_1CYCLE,
      G_AC_THRESHOLD | RM1(XLU_SURF), GFX_PRIM_TEXRECT, 0, true },
    { "threshold + opaque 2-cycle (cycle 0 alpha)", LERP(TEXEL0, 0, SHADE, 0, TEXEL0, 0, SHADE, 0, COMBINED, 0, PRIMITIVE,
                                                         0, COMBINED, 0, PRIMITIVE, 0),
      G_CYC_2CYCLE,
      G_AC_THRESHOLD | Z_CMP | Z_UPD | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | ALPHA_CVG_SEL | G_RM_PASS |
          GBL_c2(G_BL_CLR_IN, G_BL_0, G_BL_CLR_IN, G_BL_1),
      GFX_PRIM_TRIANGLE, TRI, false },
    { "threshold + AA_ZB_OPA_SURF (coverage alpha)", MODE(G_CC_MODULATEIA, G_CC_MODULATEIA), G_CYC_1CYCLE,
      G_AC_THRESHOLD | RM1(AA_ZB_OPA_SURF), GFX_PRIM_TRIANGLE, TRI, false },
    { "IN/A_IN/BL/1MA (PreRender)", MODE(G_CC_MODULATEIA_PRIM, G_CC_MODULATEIA_PRIM), G_CYC_1CYCLE,
      FORCE_BL | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_BL, G_BL_1MA) | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_BL, G_BL_1MA),
      GFX_PRIM_TEXRECT, 0, false },
    { "MEM in cycle 0 (fbdemo circle)", MODE(G_CC_MODULATEIA_PRIM, G_CC_PASS2), G_CYC_2CYCLE,
      AA_EN | IM_RD | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | FORCE_BL | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA) |
          GBL_c2(G_BL_CLR_IN, G_BL_0, G_BL_CLR_IN, G_BL_1),
      GFX_PRIM_TRIANGLE, TRI, true },
    { "BL*A_FOG + IN*1MA (K3)", MODE(G_CC_MODULATEIA, G_CC_PASS2), G_CYC_2CYCLE,
      GBL_c1(G_BL_CLR_BL, G_BL_A_FOG, G_BL_CLR_IN, G_BL_1MA) | RM_AA_ZB_OPA_SURF(2), GFX_PRIM_TRIANGLE, TRI, false },
    { "IN*A_FOG + BL*1MA (K3)", MODE(G_CC_MODULATEIA, G_CC_PASS2), G_CYC_2CYCLE,
      GBL_c1(G_BL_CLR_IN, G_BL_A_FOG, G_BL_CLR_BL, G_BL_1MA) | RM_AA_ZB_OPA_SURF(2), GFX_PRIM_TRIANGLE, TRI, false },
    { "IN*A_SHADE + MEM*1MA (shade alpha out)", MODE(G_CC_MODULATEIA_PRIM, G_CC_MODULATEIA_PRIM), G_CYC_1CYCLE,
      IM_RD | FORCE_BL | GBL_c1(G_BL_CLR_IN, G_BL_A_SHADE, G_BL_CLR_MEM, G_BL_1MA) |
          GBL_c2(G_BL_CLR_IN, G_BL_A_SHADE, G_BL_CLR_MEM, G_BL_1MA),
      GFX_PRIM_TRIANGLE, TRI, false },
    { "FOG_SHADE_A + ADD2 (fog alpha out)", MODE(G_CC_MODULATEIA, G_CC_PASS2), G_CYC_2CYCLE,
      G_RM_FOG_SHADE_A | RM_ADD(2), GFX_PRIM_TRIANGLE, TRI | G_FOG, false },
    { "MEM*A_IN + IN*1MA (dst factor alpha)", MODE(G_CC_MODULATEIA, G_CC_MODULATEIA), G_CYC_1CYCLE,
      IM_RD | FORCE_BL | GBL_c1(G_BL_CLR_MEM, G_BL_A_IN, G_BL_CLR_IN, G_BL_1MA) |
          GBL_c2(G_BL_CLR_MEM, G_BL_A_IN, G_BL_CLR_IN, G_BL_1MA),
      GFX_PRIM_TRIANGLE, TRI, false },
    /* The framebuffer times its own factors: MEM * A_IN (darken), MEM * (A_SHADE + 1) */
    { "MEM*A_IN + MEM*0", MODE(G_CC_MODULATEIA, G_CC_MODULATEIA), G_CYC_1CYCLE,
      IM_RD | FORCE_BL | GBL_c1(G_BL_CLR_MEM, G_BL_A_IN, G_BL_CLR_MEM, G_BL_0) |
          GBL_c2(G_BL_CLR_MEM, G_BL_A_IN, G_BL_CLR_MEM, G_BL_0),
      GFX_PRIM_TRIANGLE, TRI, false },
    { "MEM*A_SHADE + MEM*1", MODE(G_CC_MODULATEIA, G_CC_MODULATEIA), G_CYC_1CYCLE,
      IM_RD | FORCE_BL | GBL_c1(G_BL_CLR_MEM, G_BL_A_SHADE, G_BL_CLR_MEM, G_BL_1) |
          GBL_c2(G_BL_CLR_MEM, G_BL_A_SHADE, G_BL_CLR_MEM, G_BL_1),
      GFX_PRIM_TRIANGLE, TRI, false },
    { "BL*0 + MEM*1MA: z only", MODE(G_CC_SHADE, G_CC_SHADE), G_CYC_1CYCLE,
      G_ZS_PRIM | Z_UPD | IM_RD | CVG_DST_SAVE | ZMODE_OPA | FORCE_BL | GBL_c1(G_BL_CLR_BL, G_BL_0, G_BL_CLR_MEM, G_BL_1MA) |
          GBL_c2(G_BL_CLR_BL, G_BL_0, G_BL_CLR_MEM, G_BL_1MA),
      GFX_PRIM_TRIANGLE, TRI, false },
};

#endif
