/**
 * Link ranges of the statically linked overlays. On GameCube every spec overlay (ovl_*) is linked into the DOL
 * as one contiguous block: text, rodata, data, bss (32-byte aligned parts). The table is generated by
 * port/gc/tools/gen_gc_link.py into build/gc-n64-us/generated/ovl_ranges.c, sorted by start address.
 * Game-side header (decomp types); do not include from libogc translation units.
 */
#ifndef GC_OVERLAY_RANGES_H
#define GC_OVERLAY_RANGES_H

#include "PR/ultratypes.h"

typedef struct GcOverlayRange {
    /* 0x00 */ const char* name; // spec segment name, e.g. "ovl_En_Mag"
    /* 0x04 */ u8* start;        // _<name>SegmentStart: the N64 vramStart
    /* 0x08 */ u8* end;          // _<name>SegmentEnd: the N64 vramEnd (after .bss)
    /* 0x0C */ u8* dataStart;    // _<name>SegmentDataStart
    /* 0x10 */ u8* dataEnd;      // _<name>SegmentDataEnd
    /* 0x14 */ u8* bssStart;     // _<name>SegmentBssStart
    /* 0x18 */ u8* bssEnd;       // _<name>SegmentBssEnd
} GcOverlayRange; // size = 0x1C

extern const GcOverlayRange gGcOverlayRanges[];
extern const s32 gGcOverlayRangeCount;

#endif
