#!/usr/bin/env python3
"""Generate port/gc/gfx/gfx_gbi.h: the object-like G_* constants of the decomp's include/PR/gbi.h
(F3DEX2 with point lights), without its types and macros, which clash with libogc."""
import re
import subprocess
import sys

cmd = ["gcc", "-E", "-dM", "-xc", "-nostdinc", "-Iinclude", "-Iinclude/libc", "-D_LANGUAGE_C",
       "-DF3DEX_GBI_2", "-DF3DEX_GBI_PL", "-DGBI_DOWHILE", "-include", "include/PR/gbi.h", "/dev/null"]
macros = subprocess.run(cmd, check=True, capture_output=True, text=True).stdout.splitlines()

defs = {}
for line in macros:
    m = re.match(r"#define (G_[A-Za-z0-9_]+) (.*)$", line)  # object-like macros only
    if m:
        defs[m.group(1)] = m.group(2).strip()

def names(value):
    value = re.sub(r"\b0[xX][0-9a-fA-F]+[uUlL]*\b|\b\d+[uUlL]*\b", " ", value)  # drop numeric literals
    return re.findall(r"[A-Za-z_][A-Za-z0-9_]*", value)

kept = {}
changed = True
while changed:
    changed = False
    for name, value in defs.items():
        if name not in kept and all(n in kept for n in names(value)):
            kept[name] = value
            changed = True

out = ["/**",
       " * N64 GBI constants for F3DEX2/F3DZEX2 with point lights: opcodes, geometry and other mode bits,",
       " * combiner and blender inputs, texture formats. Generated by port/gc/tools/gen_gfx_gbi.py from the",
       " * decomp's include/PR/gbi.h. Constants only: the decomp's Gfx/Mtx/Vtx types clash with libogc's.",
       " */",
       "#ifndef GFX_GBI_H", "#define GFX_GBI_H", ""]
out += [f"#define {n} {kept[n]}" for n in defs if n in kept]
out += ["", "#endif", ""]
open("port/gc/gfx/gfx_gbi.h", "w").write("\n".join(out))
print(f"gfx_gbi.h: {len(kept)} constants ({len(defs) - len(kept)} skipped)", file=sys.stderr)
