#!/usr/bin/env python3
"""Link inputs for the GameCube build (Makefile.gc), generated from spec/spec and the matching N64 ELF.

  generate  writes into --out-dir (build/gc-n64-us):
      mm_gc.ld                 complete DOL linker script: devkitPPC's ogc.ld + libogc_common.ld layout, plus one
                               contiguous output section per spec overlay (ovl_*) holding the text, rodata, data and
                               bss of that overlay's objects, bracketed by the _<seg>Segment* symbols game code uses
      abs_syms.ld              PROVIDE() for every global N64 symbol below 0x80000000: segmented asset addresses,
                               ROM/VROM offsets (_<seg>SegmentRomStart/End), audio table offsets
      generated/ovl_ranges.c   gGcOverlayRanges[] (port/gc/include/gc_overlay_ranges.h), sorted by start address

  verify    checks a linked ELF and its map against the overlay layout the script asks for

Run from the repository root inside Linux/WSL (python3 3.8+, devkitPPC and mips-linux-gnu binutils).
"""

import argparse
import fnmatch
import hashlib
import os
import re
import subprocess
import sys

# devkitPPC (libogc 3.1.0) scripts the layout below was derived from. A different version only triggers a warning:
# compare the new libogc_common.ld with LD_SCRIPT_TEMPLATE and update both hashes.
OGC_LD_SHA256 = {
    "ogc.ld": "6461457d8e82477ca32dea877f098696405190ccd03b33a11b3ca18bcdd3422c",
    "libogc_common.ld": "268c85b97c7b4e2e3baa782b6d8953d4f37cfb2968af73ff5cc1f0c467df6569",
}

OVL_PREFIX = "ovl_"
ALIGN = 32

# Input sections of an overlay object, per part of the overlay block
OVL_PARTS = [
    ("Text", ".text .text.*"),
    ("RoData", ".rodata .rodata.* .rodata1 .sdata2 .sdata2.* .sbss2 .sbss2.*"),
    ("Data", ".data .data.* .data1 .sdata .sdata.*"),
    ("Bss", ".sbss .sbss.* .bss .bss.* COMMON"),
]

# ogc.ld + libogc_common.ld, with @X@ (exclusion of overlay objects) in front of every generic input section rule
# that could take code or data of an overlay object, and @OVERLAYS@ after .text (inside the text PT_LOAD).
LD_SCRIPT_TEMPLATE = """\
/*
 * Linker script for the GameCube build of Majora's Mask (DOL).
 * Generated by port/gc/tools/gen_gc_link.py from spec/spec; do not edit.
 *
 * Layout of devkitPPC's ogc.ld + libogc_common.ld (libogc 3.1.0), plus every spec overlay statically linked
 * as one contiguous block (text, rodata, data, bss) in the text PT_LOAD, bracketed by
 * _<seg>SegmentStart/End and _<seg>Segment{Text,RoData,Data,Bss}{Start,End}, all 32-byte aligned.
 * Overlay .bss is zero-filled in the file. Overlay objects are excluded from the generic section rules.
 */

OUTPUT_ARCH(powerpc:common)
ENTRY(__app_start)

PROVIDE_HIDDEN( __isIPL = 0 );

PROVIDE_HIDDEN( __ppc_excpt_buf   = 0x800000d0 );
PROVIDE_HIDDEN( __ppc_excpt_table = 0x80003000 );

PHDRS {
	text PT_LOAD FLAGS(5);
	data PT_LOAD FLAGS(6);
	bss  PT_LOAD;
}

SECTIONS {

	/* Default base address (ogc.ld) */
	. = 0x80003100;

	.init : {
		*(.crt0 .crt0.*)
	} :text = 0

	/* Code */
	.text : ALIGN_WITH_INPUT {
		KEEP( *(SORT_NONE(.init)) )
		@X@*(.text.unlikely .text.*_unlikely .text.unlikely.*)
		@X@*(.text.exit .text.exit.*)
		@X@*(.text.startup .text.startup.*)
		@X@*(.text.hot .text.hot.*)
		@X@*(SORT(.text.sorted.*))
		@X@*(.text .iplt .stub .text.* .gnu.linkonce.t.*)
		KEEP( *(SORT_NONE(.fini)) )
	} :text = 0

	/* ====================== */
	/*  Overlays (spec/spec)  */
	/* ====================== */
@OVERLAYS@
	. = ALIGN(32);

	/* Read-only data */
	.rodata : {
		KEEP( *(.rodata.__sys_versioninfo) )

		@X@*(.rodata .rodata.* .gnu.linkonce.r.*)
		@X@*(.rodata1)

		*(.fixup)
		*(.got1)
		*(.got2)
		*(.branch_lt)
		*(.got)
		*(.plt)
	} :data = 0

	/* Small read-only data */
	.sdata2 : ALIGN_WITH_INPUT {
		@X@*(.sdata2 .sdata2.* .gnu.linkonce.s2.*)
		@X@*(.sbss2 .sbss2.* .gnu.linkonce.sb2.*)
	} :data = 0

	/* Exception frame header */
	.eh_frame_hdr : ALIGN_WITH_INPUT {
		*(.eh_frame_hdr)
		*(.eh_frame_entry .eh_frame_entry.*)
	} :data = 0

	/* Exception frame information */
	.eh_frame : ALIGN_WITH_INPUT {
		KEEP( *(.eh_frame) )
		*(.eh_frame.*)
	} :data = 0

	/* GCC language agnostic exception table */
	.gcc_except_table : ALIGN_WITH_INPUT {
		*(.gcc_except_table .gcc_except_table.*)
	} :data = 0

	/* GNU exception table */
	.gnu_extab : ALIGN_WITH_INPUT {
		*(.gnu_extab*)
	} :data = 0

	/* Table of global constructors */
	.ctors : ALIGN_WITH_INPUT {
		KEEP( *ecrti.o(.ctors) )
		KEEP( *crtbegin.o(.ctors) )
		KEEP( *crtbegin?.o(.ctors) )
		KEEP( *(EXCLUDE_FILE(*ecrtn.o *crtend.o *crtend?.o) .ctors) )
		KEEP( *(SORT_BY_NAME(.ctors.*)) )
		KEEP( *(SORT_NONE(.ctors)) )
	} :data = 0

	/* Table of global destructors */
	.dtors : ALIGN_WITH_INPUT {
		KEEP( *ecrti.o(.dtors) )
		KEEP( *crtbegin.o(.dtors) )
		KEEP( *crtbegin?.o(.dtors) )
		KEEP( *(EXCLUDE_FILE(*ecrtn.o *crtend.o *crtend?.o) .dtors) )
		KEEP( *(SORT_BY_NAME(.dtors.*)) )
		KEEP( *(SORT_NONE(.dtors)) )
	} :data = 0

	.data : ALIGN_WITH_INPUT {
		@X@*(.data .data.* .gnu.linkonce.d.*)
		@X@*(.data1)
		SORT(CONSTRUCTORS)
	} :data = 0

	.sdata : ALIGN_WITH_INPUT {
		@X@*(.sdata .sdata.* .gnu.linkonce.s.*)
		*(.lit8)
		*(.lit4)
	} :data = 0

	.sbss . (NOLOAD) : {
		*(.dynsbss)
		@X@*(.sbss .sbss.* .gnu.linkonce.sb.*)
		*(.scommon)
	} :bss

	PROVIDE_HIDDEN( __sbss_start = ADDR(.sbss)                 );
	PROVIDE_HIDDEN( __sbss_end   = ADDR(.sbss) + SIZEOF(.sbss) );

	.bss . (NOLOAD) : {
		*(.dynbss)
		@X@*(.bss .bss.* .gnu.linkonce.b.*)
		@X@*(COMMON)
	} :bss

	PROVIDE_HIDDEN( __bss_start = ADDR(.bss)                );
	PROVIDE_HIDDEN( __bss_end   = ADDR(.bss) + SIZEOF(.bss) );

	. = .;

	PROVIDE_HIDDEN( __Arena1Lo = (. + 0x1f) &~ 0x1f );
	PROVIDE_HIDDEN( __Arena1Hi = 0x81800000         );

	/* ====================== */
	/*   Debugging metadata   */
	/* ====================== */

	/* Stabs debugging sections.  */
	.stab           0 : { *(.stab) }
	.stabstr        0 : { *(.stabstr) }
	.stab.excl      0 : { *(.stab.excl) }
	.stab.exclstr   0 : { *(.stab.exclstr) }
	.stab.index     0 : { *(.stab.index) }
	.stab.indexstr  0 : { *(.stab.indexstr) }
	.comment 0 (INFO) : { *(.comment); LINKER_VERSION; }
	.gnu.build.attributes : { *(.gnu.build.attributes .gnu.build.attributes.*) }

	/* DWARF debug sections.
	   Symbols in the DWARF debugging sections are relative to the beginning
	   of the section so we begin them at 0. */
	/* DWARF 1 */
	.debug          0 : { *(.debug) }
	.line           0 : { *(.line) }
	/* GNU DWARF 1 extensions */
	.debug_srcinfo  0 : { *(.debug_srcinfo) }
	.debug_sfnames  0 : { *(.debug_sfnames) }
	/* DWARF 1.1 and DWARF 2 */
	.debug_aranges  0 : { *(.debug_aranges) }
	.debug_pubnames 0 : { *(.debug_pubnames) }
	/* DWARF 2 */
	.debug_info     0 : { *(.debug_info .gnu.linkonce.wi.*) }
	.debug_abbrev   0 : { *(.debug_abbrev) }
	.debug_line     0 : { *(.debug_line .debug_line.* .debug_line_end) }
	.debug_frame    0 : { *(.debug_frame) }
	.debug_str      0 : { *(.debug_str) }
	.debug_loc      0 : { *(.debug_loc) }
	.debug_macinfo  0 : { *(.debug_macinfo) }
	/* SGI/MIPS DWARF 2 extensions */
	.debug_weaknames 0 : { *(.debug_weaknames) }
	.debug_funcnames 0 : { *(.debug_funcnames) }
	.debug_typenames 0 : { *(.debug_typenames) }
	.debug_varnames  0 : { *(.debug_varnames) }
	/* DWARF 3 */
	.debug_pubtypes 0 : { *(.debug_pubtypes) }
	.debug_ranges   0 : { *(.debug_ranges) }
	/* DWARF Extension.  */
	.debug_macro    0 : { *(.debug_macro) }
	.debug_addr     0 : { *(.debug_addr) }
	/* DWARF 5.  */
	.debug_addr     0 : { *(.debug_addr) }
	.debug_line_str 0 : { *(.debug_line_str) }
	.debug_loclists 0 : { *(.debug_loclists) }
	.debug_macro    0 : { *(.debug_macro) }
	.debug_names    0 : { *(.debug_names) }
	.debug_rnglists 0 : { *(.debug_rnglists) }
	.debug_str_offsets 0 : { *(.debug_str_offsets) }
	.debug_sup      0 : { *(.debug_sup) }

	/DISCARD/ : { *(.note.GNU-stack) *(.gnu_debuglink) *(.gnu.lto_*) }

}
"""

OVL_RANGES_HEADER = """\
/**
 * Link ranges of the statically linked overlays, sorted by start address (= N64 vramStart).
 * Generated by port/gc/tools/gen_gc_link.py from spec/spec; do not edit.
 */
#include "gc_overlay_ranges.h"

"""


def fail(msg):
    sys.exit(f"gen_gc_link.py: error: {msg}")


def warn(msg):
    print(f"gen_gc_link.py: warning: {msg}", file=sys.stderr)


def run(cmd):
    return subprocess.run(cmd, check=True, stdout=subprocess.PIPE, text=True, errors="replace").stdout


def write_file(path, text):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, path)


def read_obj_list(path):
    with open(path) as f:
        objs = f.read().split()
    if not objs:
        fail(f"{path} lists no objects")
    return objs


def parse_spec(spec, version, cpp):
    """Return [(segment name, [include paths])] in spec order, preprocessed like Makefile.gc does."""
    text = run([cpp, "-E", "-P", "-xc", "-fno-dollars-in-identifiers", f"-DMM_VERSION={version}", "-I.", spec])
    segments = []
    cur = None
    for lineno, line in enumerate(text.splitlines(), 1):
        words = line.split(None, 1)
        if not words:
            continue
        key = words[0]
        if key == "beginseg":
            if cur is not None:
                fail(f"spec line {lineno}: beginseg inside a segment")
            cur = [None, []]
        elif key == "endseg":
            if cur is None or cur[0] is None:
                fail(f"spec line {lineno}: endseg without a named segment")
            segments.append((cur[0], cur[1]))
            cur = None
        elif cur is not None and key == "name":
            cur[0] = words[1].strip().strip('"')
        elif cur is not None and key.startswith("include"):
            cur[1].append(words[1].strip().strip('"'))
    if cur is not None:
        fail("spec ends inside a segment")
    return segments


def overlay_groups(segments, objs, gc_build_dir):
    """Overlay segments with the GC objects they contain: [(name, [objects])] in spec order."""
    objset = set(objs)
    groups = []
    for name, includes in segments:
        if not name.startswith(OVL_PREFIX):
            continue
        members = []
        for inc in includes:
            if not inc.startswith("$(BUILD_DIR)/"):
                fail(f"segment {name}: unexpected include path {inc}")
            obj = f"{gc_build_dir}/{inc[len('$(BUILD_DIR)/'):]}"
            if obj in objset:
                members.append(obj)
        if members:
            groups.append((name, members))
    seen = {}
    for name, members in groups:
        for obj in members:
            if obj in seen:
                fail(f"{obj} is in both {seen[obj]} and {name}")
            seen[obj] = name
    return groups


def file_pattern(obj):
    # Leading '*': matches the object whether the link passes it with a relative or an absolute path
    return "*" + obj


def exclude_pattern(objs, groups, gc_build_dir):
    """EXCLUDE_FILE() for the generic rules: a directory wildcard if it selects exactly the overlay objects."""
    ovl_objs = {obj for _, members in groups for obj in members}
    pattern = f"*{gc_build_dir}/src/overlays/*"
    if {obj for obj in objs if fnmatch.fnmatchcase(obj, pattern)} == ovl_objs:
        return f"EXCLUDE_FILE({pattern}) "
    warn("overlay objects are not exactly the objects under src/overlays/; listing them one by one")
    return "EXCLUDE_FILE(" + " ".join(file_pattern(obj) for obj in sorted(ovl_objs)) + ") "


def ovl_symbol(seg, part="", edge="Start"):
    return f"_{seg}Segment{part}{edge}"


def gen_overlay_block(seg, members):
    lines = [f"\t.{seg} ALIGN({ALIGN}) : {{", f"\t\t{ovl_symbol(seg)} = .;"]
    for part, sections in OVL_PARTS:
        lines.append(f"\t\t{ovl_symbol(seg, part)} = .;")
        for obj in members:
            lines.append(f"\t\t{file_pattern(obj)}({sections})")
        lines.append(f"\t\t. = ALIGN({ALIGN});")
        lines.append(f"\t\t{ovl_symbol(seg, part, 'End')} = .;")
    lines.append(f"\t\t{ovl_symbol(seg, edge='End')} = .;")
    lines.append("\t} :text = 0")
    return "\n".join(lines) + "\n"


def gen_ld_script(groups, exclude):
    blocks = "\n".join(gen_overlay_block(seg, members) for seg, members in groups)
    return LD_SCRIPT_TEMPLATE.replace("@X@", exclude).replace("@OVERLAYS@", blocks)


def gen_ovl_ranges(groups):
    out = [OVL_RANGES_HEADER]
    fields = [("", "Start"), ("", "End"), ("Data", "Start"), ("Data", "End"), ("Bss", "Start"), ("Bss", "End")]
    for seg, _ in groups:
        out.append("extern u8 " + ", ".join(ovl_symbol(seg, p, e) + "[]" for p, e in fields) + ";\n")
    out.append("\nconst GcOverlayRange gGcOverlayRanges[] = {\n")
    for seg, _ in groups:
        out.append(f'    {{ "{seg}", ' + ", ".join(ovl_symbol(seg, p, e) for p, e in fields) + " },\n")
    out.append("};\n\n")
    out.append("const s32 gGcOverlayRangeCount = sizeof(gGcOverlayRanges) / sizeof(gGcOverlayRanges[0]);\n")
    return "".join(out)


NM_LINE = re.compile(r"^([0-9a-fA-F]+)\s+(\S)\s+(\S+)$")
LD_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_.$]*$")
LD_ASSIGN = re.compile(r"^\s*(?:PROVIDE(?:_HIDDEN)?\s*\(\s*)?([A-Za-z_.$][A-Za-z0-9_.$]*)\s*=", re.M)


def defined_globals(nm, files):
    names = set()
    if files:
        out = run([nm, "--defined-only", "-g", *files])
        for line in out.splitlines():
            m = NM_LINE.match(line.strip())
            if m:
                names.add(m.group(3))
    return names


def library_symbols(nm, libs):
    """Every symbol name (defined or undefined) of the toolchain libraries the DOL links."""
    names = set()
    for lib in libs:
        if not os.path.exists(lib):
            warn(f"library {lib} not found; not checked for name clashes")
            continue
        out = run([nm, "-g", lib])
        for line in out.splitlines():
            words = line.split()
            if len(words) >= 2 and len(words[-2]) == 1:
                names.add(words[-1])
    return names


def gen_abs_syms(args, objs):
    out = run([args.mips_nm, "--defined-only", "-g", args.n64_elf])
    syms = {}
    for line in out.splitlines():
        m = NM_LINE.match(line.strip())
        if not m:
            continue
        value = int(m.group(1), 16)
        if value < 0x80000000:
            syms.setdefault(m.group(3), value)

    skip_defined = defined_globals(args.nm, objs)
    skip_script = set()
    for path in args.extra_ld:
        with open(path) as f:
            skip_script.update(LD_ASSIGN.findall(f.read()))
    skip_libs = library_symbols(args.nm, args.lib)

    lines = [
        "/*",
        " * N64 asset/ROM symbols for the GameCube link: every global symbol of the matching N64 ELF below",
        " * 0x80000000 (segmented addresses, ROM/VROM offsets, audio table offsets), so the GameCube build keeps",
        " * the N64 VROM address space. Generated by port/gc/tools/gen_gc_link.py; do not edit.",
        " */",
    ]
    counts = {"emitted": 0, "defined by GC objects": 0, "assigned by extra scripts": 0,
              "clash with toolchain libraries": 0, "unrepresentable names": 0}
    clashes = []
    for name in sorted(syms):
        if name in skip_defined:
            counts["defined by GC objects"] += 1
        elif name in skip_script:
            counts["assigned by extra scripts"] += 1
        elif name in skip_libs:
            counts["clash with toolchain libraries"] += 1
            clashes.append(name)
        elif not LD_NAME.match(name):
            counts["unrepresentable names"] += 1
            warn(f"skipping N64 symbol with unusual name {name!r}")
        else:
            lines.append(f"PROVIDE({name} = 0x{syms[name]:08X});")
            counts["emitted"] += 1
    if clashes:
        warn(f"not providing {len(clashes)} N64 symbols that toolchain libraries also use: {' '.join(clashes[:20])}")
    print("abs_syms.ld: " + ", ".join(f"{v} {k}" for k, v in counts.items()))
    return "\n".join(lines) + "\n"


def check_ogc_scripts(ogc_lib_dir):
    for name, digest in OGC_LD_SHA256.items():
        path = os.path.join(ogc_lib_dir, name)
        try:
            with open(path, "rb") as f:
                actual = hashlib.sha256(f.read()).hexdigest()
        except FileNotFoundError:
            warn(f"{path} not found; cannot check that mm_gc.ld still matches devkitPPC's layout")
            continue
        if actual != digest:
            warn(f"{path} differs from the version mm_gc.ld was derived from; review LD_SCRIPT_TEMPLATE")


def cmd_generate(args):
    objs = read_obj_list(args.objs)
    gc_build_dir = args.gc_build_dir or args.out_dir
    check_ogc_scripts(args.ogc_lib_dir)

    groups = overlay_groups(parse_spec(args.spec, args.version, args.cpp), objs, gc_build_dir)
    if not groups:
        fail("no overlay segments found")
    exclude = exclude_pattern(objs, groups, gc_build_dir)

    write_file(os.path.join(args.out_dir, "mm_gc.ld"), gen_ld_script(groups, exclude))
    write_file(os.path.join(args.out_dir, "generated", "ovl_ranges.c"), gen_ovl_ranges(groups))
    write_file(os.path.join(args.out_dir, "abs_syms.ld"), gen_abs_syms(args, objs))
    nobjs = sum(len(m) for _, m in groups)
    print(f"mm_gc.ld: {len(groups)} overlay groups ({nobjs} objects), ovl_ranges.c: {len(groups)} entries")


#### verify ####

MAP_INPUT = re.compile(r"^ (\.\S+|COMMON)(?:\s+0x([0-9a-fA-F]+)\s+0x([0-9a-fA-F]+)\s+(\S.*))?$")
MAP_CONT = re.compile(r"^\s+0x([0-9a-fA-F]+)\s+0x([0-9a-fA-F]+)\s+(\S.*)$")
MAP_OUTPUT = re.compile(r"^(\.\S+|COMMON)(?:\s+0x([0-9a-fA-F]+)\s+0x([0-9a-fA-F]+).*)?$")


def parse_map(path):
    """Input section placements from a GNU ld map: [(output section, input section, addr, size, file)]."""
    entries = []
    out_sec = None
    pending = None
    in_layout = False
    with open(path, errors="replace") as f:
        for line in f:
            line = line.rstrip("\n")
            if not in_layout:
                in_layout = line.startswith("Linker script and memory map")
                continue
            if pending is not None:
                m = MAP_CONT.match(line)
                if m:
                    entries.append((out_sec, pending, int(m.group(1), 16), int(m.group(2), 16), m.group(3).strip()))
                pending = None
                continue
            m = MAP_OUTPUT.match(line)
            if m:
                out_sec = m.group(1)
                continue
            m = MAP_INPUT.match(line)
            if m:
                if m.group(2) is None:
                    pending = m.group(1)
                else:
                    entries.append((out_sec, m.group(1), int(m.group(2), 16), int(m.group(3), 16),
                                    m.group(4).strip()))
    return entries


def cmd_verify(args):
    objs = read_obj_list(args.objs)
    gc_build_dir = args.gc_build_dir or os.path.dirname(args.objs)
    groups = overlay_groups(parse_spec(args.spec, args.version, args.cpp), objs, gc_build_dir)

    syms = {}
    for line in run([args.nm, args.elf]).splitlines():
        m = NM_LINE.match(line.strip())
        if m:
            syms[m.group(3)] = int(m.group(1), 16)

    errors = []
    prev_end = None
    obj_group = {}
    ranges = {}
    totals = dict.fromkeys([p for p, _ in OVL_PARTS], 0)
    for seg, members in groups:
        names = [ovl_symbol(seg)] + [ovl_symbol(seg, p, e) for p, _ in OVL_PARTS for e in ("Start", "End")]
        names.append(ovl_symbol(seg, edge="End"))
        missing = [n for n in names if n not in syms]
        if missing:
            errors.append(f"{seg}: missing symbols {missing}")
            continue
        values = [syms[n] for n in names]
        if any(v % ALIGN for v in values):
            errors.append(f"{seg}: symbols not {ALIGN}-byte aligned")
        if values != sorted(values) or values[0] != values[1] or values[-1] != values[-2]:
            errors.append(f"{seg}: symbols out of order: " + " ".join(f"{v:08X}" for v in values))
        if prev_end is not None and values[0] < prev_end:
            errors.append(f"{seg}: starts at {values[0]:08X}, before the previous overlay ends ({prev_end:08X})")
        prev_end = values[-1]
        ranges[seg] = (values[0], values[-1])
        for i, (part, _) in enumerate(OVL_PARTS):
            totals[part] += values[2 + 2 * i] - values[1 + 2 * i]
        for obj in members:
            obj_group[obj] = seg

    # Every allocated piece of an overlay object must lie inside its own overlay block
    placed = 0
    for out_sec, in_sec, addr, size, path in parse_map(args.map):
        if size == 0 or not in_sec.startswith((".text", ".rodata", ".data", ".bss", ".sdata", ".sbss", "COMMON")):
            continue
        seg = next((obj_group[o] for o in (path, os.path.relpath(path)) if o in obj_group), None)
        if seg is None:
            if "/src/overlays/" in path:
                errors.append(f"{path}({in_sec}) is from src/overlays/ but in no overlay group")
            continue
        start, end = ranges.get(seg, (0, 0))
        if out_sec != "." + seg or not (start <= addr and addr + size <= end):
            errors.append(f"{path}({in_sec}) at {addr:08X} is in {out_sec}, not in {seg} [{start:08X}, {end:08X})")
        placed += 1

    if placed == 0:
        errors.append(f"{args.map}: no overlay input sections found (map format not understood?)")
    for e in errors[:50]:
        print(f"verify: {e}", file=sys.stderr)
    if errors:
        fail(f"{len(errors)} overlay layout errors")
    first = min(s for s, _ in ranges.values())
    last = max(e for _, e in ranges.values())
    print(f"verify: {len(ranges)} overlay groups OK, {placed} input sections placed, "
          f"[{first:08X}, {last:08X}) = {last - first} bytes ("
          + ", ".join(f"{p.lower()} {n}" for p, n in totals.items()) + ")")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    devkitpro = os.environ.get("DEVKITPRO", "/opt/devkitpro")
    for name in ("generate", "verify"):
        p = sub.add_parser(name)
        p.add_argument("--objs", required=True, help="file listing the GC game objects (Makefile.gc GAME_O_FILES)")
        p.add_argument("--spec", default="spec/spec")
        p.add_argument("--version", default="N64_US", help="MM_VERSION used to preprocess the spec")
        p.add_argument("--cpp", default="gcc", help="host C compiler used to preprocess the spec")
        p.add_argument("--gc-build-dir", help="prefix of the GC object paths (default: --out-dir / objs list dir)")
        p.add_argument("--nm", default=f"{devkitpro}/devkitPPC/bin/powerpc-eabi-nm")
        if name == "generate":
            p.add_argument("--out-dir", default="build/gc-n64-us")
            p.add_argument("--n64-elf", default="build/n64-us/mm-n64-us.elf")
            p.add_argument("--mips-nm", default="mips-linux-gnu-nm")
            p.add_argument("--extra-ld", action="append", default=[],
                           help="other linker scripts of the link; symbols they assign are not PROVIDEd")
            p.add_argument("--lib", action="append", default=[],
                           help="toolchain library; N64 symbols whose names it uses are not PROVIDEd")
            p.add_argument("--ogc-lib-dir", default=f"{devkitpro}/devkitPPC/powerpc-eabi/lib")
        else:
            p.add_argument("--elf", required=True)
            p.add_argument("--map", required=True)
    args = parser.parse_args()
    if args.cmd == "generate":
        cmd_generate(args)
    else:
        cmd_verify(args)


if __name__ == "__main__":
    main()
