#!/usr/bin/env python3
"""Write a C table of the CRC32 of every 64 KB of the ROM, for the GC_ROM_CHECK=1 self-test (bridge_rom.c).

The table holds checksums only, no ROM data. It is generated into the build directory from the build
machine's baserom and must not be committed (it identifies one ROM).
"""
import argparse
import zlib


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rom", required=True, help="baserom.z64")
    parser.add_argument("--chunk", type=int, default=0x10000, help="bytes per checksum (default 64 KB)")
    parser.add_argument("-o", "--output", required=True, help="C file to write")
    args = parser.parse_args()

    with open(args.rom, "rb") as f:
        rom = f.read()
    crcs = [zlib.crc32(rom[i : i + args.chunk]) & 0xFFFFFFFF for i in range(0, len(rom), args.chunk)]

    lines = [
        "/* Generated by port/gc/tools/gen_rom_crc.py from the build machine's baserom: the CRC32 of every",
        " * %u bytes of the %u-byte ROM, for the GC_ROM_CHECK self-test. Not to be committed. */" % (args.chunk, len(rom)),
        "const unsigned int gGcRomCheckSize = %uu;" % len(rom),
        "const unsigned int gGcRomCheckChunk = %uu;" % args.chunk,
        "const unsigned int gGcRomCheckCount = %uu;" % len(crcs),
        "const unsigned int gGcRomCheckCrc[%u] = {" % len(crcs),
    ]
    for i in range(0, len(crcs), 8):
        lines.append("    " + ", ".join("0x%08Xu" % c for c in crcs[i : i + 8]) + ",")
    lines.append("};")
    with open(args.output, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
