/**
 * N64 GBI constants for F3DEX2/F3DZEX2 with point lights: opcodes, geometry and other mode bits,
 * combiner and blender inputs, texture formats. Generated by port/gc/tools/gen_gfx_gbi.py from the
 * decomp's include/PR/gbi.h. Constants only: the decomp's Gfx/Mtx/Vtx types clash with libogc's.
 */
#ifndef GFX_GBI_H
#define GFX_GBI_H

#define G_ACMUX_0 7
#define G_MWO_CLIP_RNX 0x04
#define G_MWO_CLIP_RNY 0x0C
#define G_BRANCH_Z 0x04
#define G_MTX_MUL 0x00
#define G_MWO_CLIP_RPX 0x14
#define G_MWO_CLIP_RPY 0x1C
#define G_POPMTX 0xD8
#define G_IM_SIZ_4b_LOAD_BLOCK G_IM_SIZ_16b
#define G_RDPPIPESYNC 0xE7
#define G_IM_SIZ_DD 5
#define G_CCMUX_TEXEL0_ALPHA 8
#define G_SETCOMBINE 0xFC
#define G_FILLRECT 0xF6
#define G_TL_LOD (1 << G_MDSFT_TEXTLOD)
#define G_CYC_COPY (2 << G_MDSFT_CYCLETYPE)
#define G_CCMUX_COMBINED 0
#define G_AD_NOISE (2 << G_MDSFT_ALPHADITHER)
#define G_MDSFT_TEXTCONV 9
#define G_TEXRECT 0xE4
#define G_MVO_LOOKATX (0 * 24)
#define G_TF_POINT (0 << G_MDSFT_TEXTFILT)
#define G_MTX_NOPUSH 0x00
#define G_TX_LOADTILE 7
#define G_TL_TILE (0 << G_MDSFT_TEXTLOD)
#define G_MOVEWORD 0xDB
#define G_IM_SIZ_32b_BYTES 4
#define G_IMMCMDSIZ 64
#define G_MTX_PUSH 0x01
#define G_RDP_TRI_FILL_MASK 0x08
#define G_MVO_L1 (3 * 24)
#define G_MVO_L2 (4 * 24)
#define G_MVO_L3 (5 * 24)
#define G_MVO_L4 (6 * 24)
#define G_MVO_L5 (7 * 24)
#define G_MVO_L7 (9 * 24)
#define G_VTX 0x01
#define G_SETTILESIZE 0xF2
#define G_TRI_SHADE_ZBUFF 0xCD
#define G_MAXZ 0x03FF
#define G_MWO_MATRIX_YZ_YW_F 0x2C
#define G_MWO_MATRIX_YZ_YW_I 0x0C
#define G_MDSFT_BLENDMASK 0
#define G_MDSFT_RENDERMODE 3
#define G_DL_PUSH 0
#define G_CCMUX_SCALE 6
#define G_OFF (0)
#define G_TRI_SHADE_TXTR_ZBUFF 0xCF
#define G_IM_SIZ_32b_LOAD_BLOCK G_IM_SIZ_32b
#define G_GEOMETRYMODE 0xD9
#define G_TRI_SHADE 0xCC
#define G_MWO_bLIGHT_2 0x1C
#define G_CK_KEY (1 << G_MDSFT_COMBKEY)
#define G_IM_SIZ_4b_SHIFT 2
#define G_TRI2 0x06
#define G_DL_NOPUSH 1
#define G_IM_SIZ_8b 1
#define G_MWO_NUMLIGHT 0x00
#define G_SETBLENDCOLOR 0xF9
#define G_CCMUX_ENV_ALPHA 12
#define G_MV_POINT 12
#define G_MWO_POINT_ST 0x14
#define G_CCMUX_PRIM_LOD_FRAC 14
#define G_SHADE 0x00000004
#define G_IM_FMT_IA 3
#define G_LIGHTING 0x00020000
#define G_TC_FILT (6 << G_MDSFT_TEXTCONV)
#define G_BL_CLR_BL 2
#define G_TRI1 0x05
#define G_TX_LDBLK_MAX_TXL 2047
#define G_MWO_MATRIX_YX_YY_F 0x28
#define G_TEXTURE 0xD7
#define G_BL_1 2
#define G_MW_NUMLIGHT 0x02
#define G_BL_CLR_IN 0
#define G_SETTIMG 0xFD
#define G_CK_NONE (0 << G_MDSFT_COMBKEY)
#define G_TX_DXT_FRAC 11
#define G_MVO_L6 (8 * 24)
#define G_ZS_PIXEL (0 << G_MDSFT_ZSRCSEL)
#define G_MWO_POINT_XYSCREEN 0x18
#define G_MWO_MATRIX_XZ_XW_F 0x24
#define G_MWO_MATRIX_XZ_XW_I 0x04
#define G_NOOP 0x00
#define G_IM_SIZ_16b_INCR 0
#define G_MW_PERSPNORM 0x0E
#define G_RDP_TRI_TXTR_MASK 0x02
#define G_TT_NONE (0 << G_MDSFT_TEXTLUT)
#define G_CCMUX_CENTER 6
#define G_RDP_ADDR_FIXUP 3
#define G_TX_NOMIRROR (0 << 0)
#define G_BL_A_FOG 1
#define G_MDSFT_RGBDITHER 6
#define G_CV_K0 175
#define G_CV_K1 -43
#define G_CV_K2 -89
#define G_CV_K3 222
#define G_CV_K5 42
#define G_AD_NOTPATTERN (1 << G_MDSFT_ALPHADITHER)
#define G_MDSFT_CYCLETYPE 20
#define G_CULL_BACK 0x00000400
#define G_MOVEMEM 0xDC
#define G_TEXTURE_IMAGE_FRAC 2
#define G_CCMUX_COMBINED_ALPHA 7
#define G_MV_PMTX 6
#define G_MWO_MATRIX_ZX_ZY_F 0x30
#define G_MWO_MATRIX_ZX_ZY_I 0x10
#define G_TX_NOMASK 0
#define G_MWO_aLIGHT_1 0x00
#define G_IM_FMT_YUV 1
#define G_LOAD_UCODE 0xDD
#define G_CULL_FRONT 0x00000200
#define G_MWO_aLIGHT_7 0x90
#define G_SETPRIMDEPTH 0xEE
#define G_MW_MATRIX 0x00
#define G_BL_CLR_MEM 1
#define G_CYC_1CYCLE (0 << G_MDSFT_CYCLETYPE)
#define G_IM_SIZ_16b 2
#define G_CD_MAGICSQ (0 << G_MDSFT_RGBDITHER)
#define G_LOD 0x00100000
#define G_TEXRECTFLIP 0xE5
#define G_IM_FMT_RGBA 0
#define G_CD_NOISE (2 << G_MDSFT_RGBDITHER)
#define G_MWO_bLIGHT_1 0x04
#define G_MWO_bLIGHT_3 0x34
#define G_MWO_bLIGHT_4 0x4C
#define G_MWO_bLIGHT_5 0x64
#define G_MWO_bLIGHT_6 0x7C
#define G_MWO_bLIGHT_8 0xAC
#define G_MW_SEGMENT 0x06
#define G_MDSFT_ZSRCSEL 2
#define G_MDSFT_TEXTDETAIL 17
#define G_RDP_TRI_ZBUFF_MASK 0x01
#define G_TF_AVERAGE (3 << G_MDSFT_TEXTFILT)
#define G_SPNOOP 0xE0
#define G_MDSFT_PIPELINE 23
#define G_SC_ODD_INTERLACE 3
#define G_AC_NONE (0 << G_MDSFT_ALPHACOMPARE)
#define G_CCMUX_SHADE 4
#define G_MVO_L0 (2 * 24)
#define G_RDP_TRI_SHADE_MASK 0x04
#define G_IM_SIZ_8b_SHIFT 1
#define G_CCMUX_TEXEL0 1
#define G_CCMUX_TEXEL1 2
#define G_ACMUX_ENVIRONMENT 5
#define G_MWO_MATRIX_WZ_WW_F 0x3C
#define G_MWO_MATRIX_WZ_WW_I 0x1C
#define G_CCMUX_LOD_FRACTION 13
#define G_TRI_TXTR_ZBUFF 0xCB
#define G_CYC_2CYCLE (1 << G_MDSFT_CYCLETYPE)
#define G_IM_FMT_CI 2
#define G_SC_EVEN_INTERLACE 2
#define G_SETFILLCOLOR 0xF7
#define G_MW_CLIP 0x04
#define G_CYC_FILL (3 << G_MDSFT_CYCLETYPE)
#define G_SPECIAL_2 0xD4
#define G_SPECIAL_3 0xD3
#define G_SETKEYR 0xEB
#define G_CULL_BOTH 0x00000600
#define G_BL_CLR_FOG 3
#define G_IM_SIZ_32b_TILE_BYTES 2
#define G_BL_0 3
#define G_IM_SIZ_4b_BYTES 0
#define G_IM_SIZ_8b_LINE_BYTES G_IM_SIZ_8b_BYTES
#define G_IM_SIZ_16b_SHIFT 0
#define G_CD_DISABLE (3 << G_MDSFT_RGBDITHER)
#define G_ROTATE_FRAC 16
#define G_CD_ENABLE G_CD_NOISE
#define G_DMACMDSIZ 128
#define G_TC_CONV (0 << G_MDSFT_TEXTCONV)
#define G_TRI_FILL 0xC8
#define G_BL_A_IN 0
#define G_ACMUX_PRIMITIVE 3
#define G_TD_SHARPEN (1 << G_MDSFT_TEXTDETAIL)
#define G_CCMUX_SHADE_ALPHA 11
#define G_CCMUX_0 31
#define G_CCMUX_1 6
#define G_CCMUX_TEXEL1_ALPHA 9
#define G_PM_NPRIMITIVE (0 << G_MDSFT_PIPELINE)
#define G_IM_SIZ_16b_LINE_BYTES G_IM_SIZ_16b_BYTES
#define G_MV_MATRIX 14
#define G_CLIPPING 0x00800000
#define G_SPECIAL_1 0xD5
#define G_PM_1PRIMITIVE (1 << G_MDSFT_PIPELINE)
#define G_CCMUX_ENVIRONMENT 5
#define G_IM_SIZ_32b 3
#define G_LOADTLUT 0xF0
#define G_MDSFT_COMBKEY 8
#define G_TEXTURE_ENABLE 0x00000000
#define G_MWO_aLIGHT_2 0x18
#define G_MWO_aLIGHT_3 0x30
#define G_MWO_aLIGHT_4 0x48
#define G_MWO_aLIGHT_5 0x60
#define G_MWO_aLIGHT_6 0x78
#define G_MWO_aLIGHT_8 0xA8
#define G_CD_BAYER (1 << G_MDSFT_RGBDITHER)
#define G_MWO_SEGMENT_0 0x00
#define G_MWO_SEGMENT_2 0x02
#define G_MWO_SEGMENT_3 0x03
#define G_MWO_SEGMENT_4 0x04
#define G_MWO_SEGMENT_5 0x05
#define G_MWO_SEGMENT_6 0x06
#define G_MWO_SEGMENT_7 0x07
#define G_MWO_SEGMENT_8 0x08
#define G_MWO_SEGMENT_9 0x09
#define G_RDPSETOTHERMODE 0xEF
#define G_MWO_SEGMENT_A 0x0A
#define G_MWO_SEGMENT_B 0x0B
#define G_MWO_SEGMENT_C 0x0C
#define G_MWO_SEGMENT_D 0x0D
#define G_MWO_SEGMENT_E 0x0E
#define G_MWO_SEGMENT_F 0x0F
#define G_TEXTURE_GEN_LINEAR 0x00080000
#define G_BZ_ORTHO 1
#define G_TX_CLAMP (1 << 1)
#define G_MWO_MATRIX_XX_XY_F 0x20
#define G_MDSFT_TEXTFILT 12
#define G_SETOTHERMODE_H 0xE3
#define G_SETOTHERMODE_L 0xE2
#define G_MDSFT_TEXTPERSP 19
#define G_IM_FMT_I 4
#define G_ACMUX_LOD_FRACTION 0
#define G_AD_PATTERN (0 << G_MDSFT_ALPHADITHER)
#define G_IM_SIZ_8b_INCR 1
#define G_TT_IA16 (3 << G_MDSFT_TEXTLUT)
#define G_BL_A_SHADE 2
#define G_SETFOGCOLOR 0xF8
#define G_TF_BILERP (2 << G_MDSFT_TEXTFILT)
#define G_MWO_MATRIX_XX_XY_I 0x00
#define G_TRI_TXTR 0xCA
#define G_MTX 0xDA
#define G_AC_THRESHOLD (1 << G_MDSFT_ALPHACOMPARE)
#define G_RDPHALF_1 0xE1
#define G_RDPHALF_2 0xF1
#define G_MVO_LOOKATY (1 * 24)
#define G_RDPLOADSYNC 0xE6
#define G_IM_SIZ_4b_INCR 3
#define G_BZ_PERSP 0
#define G_IM_SIZ_4b_LINE_BYTES G_IM_SIZ_4b_BYTES
#define G_SETCONVERT 0xEC
#define G_LOADTILE 0xF4
#define G_TRI_SHADE_TXTR 0xCE
#define G_FOG 0x00010000
#define G_CV_K4 114
#define G_CCMUX_NOISE 7
#define G_SETTILE 0xF5
#define G_LOADBLOCK 0xF3
#define G_ZS_PRIM (1 << G_MDSFT_ZSRCSEL)
#define G_MDSFT_BLENDER 16
#define G_TRI_FILL_ZBUFF 0xC9
#define G_ACMUX_PRIM_LOD_FRAC 6
#define G_TX_WRAP (0 << 1)
#define G_IM_SIZ_8b_TILE_BYTES G_IM_SIZ_8b_BYTES
#define G_MODIFYVTX 0x02
#define G_MWO_FOG 0x00
#define G_ACMUX_1 6
#define G_TD_CLAMP (0 << G_MDSFT_TEXTDETAIL)
#define G_MV_LIGHT 10
#define G_IM_SIZ_8b_BYTES 1
#define G_SETENVCOLOR 0xFB
#define G_ACMUX_TEXEL0 1
#define G_ACMUX_TEXEL1 2
#define G_MW_FORCEMTX 0x0C
#define G_MWO_MATRIX_WX_WY_F 0x38
#define G_MWO_MATRIX_WX_WY_I 0x18
#define G_MTX_PROJECTION 0x04
#define G_MTX_MODELVIEW 0x00
#define G_MV_VIEWPORT 8
#define G_MV_MMTX 2
#define G_SC_NON_INTERLACE 0
#define G_IM_SIZ_32b_LINE_BYTES 2
#define G_IM_SIZ_4b 0
#define G_CCMUX_PRIMITIVE_ALPHA 10
#define G_IM_SIZ_8b_LOAD_BLOCK G_IM_SIZ_16b
#define G_MDSFT_ALPHADITHER 4
#define G_SETSCISSOR 0xED
#define G_RDPFULLSYNC 0xE9
#define G_IM_SIZ_16b_TILE_BYTES G_IM_SIZ_16b_BYTES
#define G_CCMUX_K4 7
#define G_CCMUX_K5 15
#define G_IM_SIZ_16b_BYTES 2
#define G_SETKEYGB 0xEA
#define G_MDSFT_TEXTLOD 16
#define G_IM_SIZ_16b_LOAD_BLOCK G_IM_SIZ_16b
#define G_MWO_MATRIX_YX_YY_I 0x08
#define G_AC_DITHER (3 << G_MDSFT_ALPHACOMPARE)
#define G_TX_NOLOD 0
#define G_SETZIMG 0xFE
#define G_TC_FILTCONV (5 << G_MDSFT_TEXTCONV)
#define G_DL 0xDE
#define G_SETPRIMCOLOR 0xFA
#define G_ENDDL 0xDF
#define G_MDSFT_TEXTLUT 14
#define G_MWO_SEGMENT_1 0x01
#define G_TP_PERSP (1 << G_MDSFT_TEXTPERSP)
#define G_DMA_IO 0xD6
#define G_MWO_POINT_RGBA 0x10
#define G_RDPTILESYNC 0xE8
#define G_BL_1MA 0
#define G_RDPCMDSIZ 64
#define G_CULLDL 0x03
#define G_MW_LIGHTCOL 0x0A
#define G_MDSFT_COLORDITHER 22
#define G_ON (1)
#define G_MW_FOG 0x08
#define G_MDSFT_ALPHACOMPARE 0
#define G_TEXTURE_GEN 0x00040000
#define G_IM_SIZ_4b_TILE_BYTES G_IM_SIZ_4b_BYTES
#define G_ZBUFFER 0x00000001
#define G_TEXTURE_SCALE_FRAC 16
#define G_QUAD 0x07
#define G_BL_A_MEM 1
#define G_MWO_bLIGHT_7 0x94
#define G_MWO_POINT_ZSCREEN 0x1C
#define G_LIGHTING_POSITIONAL 0x00400000
#define G_CCMUX_PRIMITIVE 3
#define G_TX_RENDERTILE 0
#define G_MTX_LOAD 0x02
#define G_ACMUX_COMBINED 0
#define G_AD_DISABLE (3 << G_MDSFT_ALPHADITHER)
#define G_IM_SIZ_32b_INCR 0
#define G_LINE3D 0x08
#define G_TT_RGBA16 (2 << G_MDSFT_TEXTLUT)
#define G_SHADING_SMOOTH 0x00200000
#define G_MWO_MATRIX_ZZ_ZW_F 0x34
#define G_ACMUX_SHADE 4
#define G_MWO_MATRIX_ZZ_ZW_I 0x14
#define G_SCALE_FRAC 8
#define G_TD_DETAIL (2 << G_MDSFT_TEXTDETAIL)
#define G_MAXFBZ 0x3FFF
#define G_IM_SIZ_32b_SHIFT 0
#define G_SETCIMG 0xFF
#define G_TX_MIRROR (1 << 0)
#define G_TP_NONE (0 << G_MDSFT_TEXTPERSP)

#endif
