/**
 * Host test of the CPU JPEG task (port/gc/game/njpeg_cpu.c, run through njpeg_shim.c): macroblocks of quantized
 * coefficients in zigzag order against a double precision reference built from the definitions (dequantization,
 * the zigzag order generated by walking the diagonals, the 8x8 inverse DCT formula, JFIF YUV -> RGB, RGBA5551),
 * in both modes (2: 16x16 tiles with chroma halved both ways, 0: 16x8 tiles with chroma halved horizontally), the
 * tile layout over each macroblock's buffer, and several macroblocks in one task.
 */
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void NJpegTest_Run(void* address, uint32_t mbCount, uint32_t mode, void* qY, void* qU, void* qV);

static int sChecks, sFailures;

#define CHECK(cond, ...)                                     \
    do {                                                     \
        sChecks++;                                           \
        if (!(cond)) {                                       \
            sFailures++;                                     \
            printf("FAIL %s:%d: ", __FILE__, __LINE__);      \
            printf(__VA_ARGS__);                             \
            printf("\n");                                    \
        }                                                    \
    } while (0)

#define MB_WORDS (6 * 64) /* JpegWork.data[i]: u16[0x180] per macroblock */

static int sZigzag[64]; /* raster index of each zigzag position */
static uint32_t sRand = 0x2468ACE1;

static uint32_t rnd(void) {
    sRand ^= sRand << 13;
    sRand ^= sRand >> 17;
    sRand ^= sRand << 5;
    return sRand;
}

/* JPEG's zigzag: diagonals row + col = d, odd ones from the top right, even ones from the bottom left */
static void build_zigzag(void) {
    int d, i, k = 0;

    for (d = 0; d < 15; d++) {
        for (i = 0; i <= d; i++) {
            int row = (d & 1) ? i : d - i, col = d - row;

            if (row < 8 && col < 8) {
                sZigzag[k++] = row * 8 + col;
            }
        }
    }
}

/* One block: dequantized (s16, times 16), inverse DCT from the definition, truncated as the task does */
static void ref_block(const int16_t* coef, const uint16_t* q, int out[64]) {
    double f[64] = { 0 };
    int k, x, y, u, v;

    for (k = 0; k < 64; k++) {
        int32_t c = coef[k] * (int16_t)q[k];

        c = (c < -32768) ? -32768 : (c > 32767) ? 32767 : c;
        f[sZigzag[k]] = (int16_t)(c * 16);
    }
    for (y = 0; y < 8; y++) {
        for (x = 0; x < 8; x++) {
            double sum = 0.0, e;

            for (v = 0; v < 8; v++) {
                for (u = 0; u < 8; u++) {
                    double cu = (u == 0) ? sqrt(0.5) : 1.0, cv = (v == 0) ? sqrt(0.5) : 1.0;

                    sum += cu * cv * f[v * 8 + u] * cos((2 * x + 1) * u * M_PI / 16.0) *
                           cos((2 * y + 1) * v * M_PI / 16.0);
                }
            }
            e = sum / 4.0 * 8.0;
            e = (e < -32768.0) ? -32768.0 : (e > 32767.0) ? 32767.0 : e;
            out[y * 8 + x] = (int16_t)e >> 3;
        }
    }
}

static int ref_channel(double c) {
    if (!(c > 0.0)) {
        return 0;
    }
    return ((c > 4080.0) ? 4080 : (int)c) & 0xF80;
}

static uint16_t ref_pixel(int y, int u, int v) {
    double fy = y + 2048.0;

    return (uint16_t)((ref_channel(fy + 1.4025 * v) << 4) | (ref_channel(fy - 0.3443 * u - 0.7144 * v) >> 1) |
                      (ref_channel(fy + 1.7729 * u) >> 6) | 1);
}

/* The task's output tile for macroblock coefficients `mb` */
static void ref_macroblock(const int16_t* mb, int mode, uint16_t q[3][64], uint16_t* out) {
    int blk[6][64];
    int blocks = mode + 4, b, x, y;

    for (b = 0; b < blocks; b++) {
        ref_block(&mb[b * 64], q[(b < blocks - 2) ? 0 : (b == blocks - 2) ? 1 : 2], blk[b]);
    }
    for (y = 0; y < ((mode == 2) ? 16 : 8); y++) {
        for (x = 0; x < 16; x++) {
            int luma, c;

            if (mode == 2) {
                luma = blk[(y >> 3) * 2 + (x >> 3)][(y & 7) * 8 + (x & 7)];
                c = (y >> 1) * 8 + (x >> 1);
                out[y * 16 + x] = ref_pixel(luma, blk[4][c], blk[5][c]);
            } else {
                luma = blk[x >> 3][y * 8 + (x & 7)];
                c = y * 8 + (x >> 1);
                out[y * 16 + x] = ref_pixel(luma, blk[2][c], blk[3][c]);
            }
        }
    }
}

/* Channels of two RGBA5551 pixels at most `tol` steps apart, alpha equal */
static int pixel_close(uint16_t a, uint16_t b, int tol) {
    int s;

    for (s = 1; s < 16; s += 5) {
        int ca = (a >> s) & 0x1F, cb = (b >> s) & 0x1F;

        if (abs(ca - cb) > tol) {
            return 0;
        }
    }
    return (a & 1) == (b & 1);
}

static void fill_tables(uint16_t q[3][64], int scale) {
    int t, k;

    for (t = 0; t < 3; t++) {
        for (k = 0; k < 64; k++) {
            q[t][k] = (uint16_t)(1 + (k * scale) / 16 + t);
        }
    }
}

/* Coefficients like a JPEG's: a DC term, a few AC terms that shrink with frequency, mostly zeros */
static void fill_coefficients(int16_t* mb, int blocks) {
    int b, k;

    for (b = 0; b < blocks; b++) {
        for (k = 0; k < 64; k++) {
            int amp = (k == 0) ? 80 : (k < 10) ? 12 : (k < 30) ? 4 : 1;

            mb[b * 64 + k] = ((rnd() % 3) == 0 || k == 0) ? (int16_t)((int)(rnd() % (2 * amp + 1)) - amp) : 0;
        }
    }
}

/* Flat blocks: each Y block one level, U and V one each, so the layout of the tile is visible */
static void test_layout(int mode) {
    static uint16_t buf[2 * MB_WORDS];
    uint16_t q[3][64], expect[256];
    int16_t* mb = (int16_t*)buf;
    int blocks = mode + 4, b, x, y, bad = 0;

    memset(buf, 0, sizeof(buf));
    fill_tables(q, 0); // Y 1, U 2, V 3
    for (b = 0; b < blocks - 2; b++) {
        mb[b * 64] = (int16_t)(-300 + 200 * b); // DC of each Y block: levels 5-bit steps apart
    }
    mb[(blocks - 2) * 64] = 20;  // U
    mb[(blocks - 1) * 64] = -15; // V
    // A second macroblock, the same, right after the first: macroblocks are (mode + 4) blocks apart, as
    // JpegDecoder_Decode writes them
    memcpy(&buf[blocks * 64], buf, (size_t)blocks * 64 * sizeof(uint16_t));
    ref_macroblock(mb, mode, q, expect);
    NJpegTest_Run(buf, 2, (uint32_t)mode, q[0], q[1], q[2]);
    for (y = 0; y < ((mode == 2) ? 16 : 8); y++) {
        for (x = 0; x < 16; x++) {
            bad += !pixel_close(buf[y * 16 + x], expect[y * 16 + x], 0);
            bad += !pixel_close(buf[blocks * 64 + y * 16 + x], expect[y * 16 + x], 0);
        }
    }
    CHECK(bad == 0, "mode %d flat blocks: %d pixels differ (first %04X, expected %04X)", mode, bad, buf[0], expect[0]);
    // The Y blocks' levels are in their quadrants (mode 2) or halves (mode 0)
    CHECK(buf[0] != buf[15] && ((mode == 0) || buf[0] != buf[15 * 16]), "mode %d: blocks placed apart", mode);
}

static void test_random(int mode) {
    static uint16_t buf[4 * MB_WORDS];
    static int16_t coef[4 * MB_WORDS];
    uint16_t q[3][64], expect[256];
    int blocks = mode + 4, n, i, bad = 0, off = 0, rows = (mode == 2) ? 16 : 8;

    fill_tables(q, 3);
    for (n = 0; n < 4; n++) {
        fill_coefficients(&coef[n * MB_WORDS], blocks);
    }
    // The task reads macroblocks of (mode + 4) blocks back to back
    for (n = 0; n < 4; n++) {
        memcpy((int16_t*)buf + n * blocks * 64, &coef[n * MB_WORDS], (size_t)blocks * 64 * sizeof(int16_t));
    }
    NJpegTest_Run(buf, 4, (uint32_t)mode, q[0], q[1], q[2]);
    for (n = 0; n < 4; n++) {
        ref_macroblock(&coef[n * MB_WORDS], mode, q, expect);
        for (i = 0; i < rows * 16; i++) {
            uint16_t got = buf[n * blocks * 64 + i];

            bad += !pixel_close(got, expect[i], 1);
            off += got != expect[i];
        }
    }
    // Float rounding may move a value across a 5-bit step, rarely
    CHECK(bad == 0 && off * 50 < 4 * rows * 16, "mode %d random macroblocks: %d pixels off by more than one step, "
          "%d not identical", mode, bad, off);
}

int main(void) {
    build_zigzag();
    CHECK(sZigzag[1] == 1 && sZigzag[2] == 8 && sZigzag[3] == 16 && sZigzag[63] == 63, "zigzag order");
    test_layout(2);
    test_layout(0);
    test_random(2);
    test_random(0);
    printf("njpeg host test: %d checks, %d failures\n", sChecks, sFailures);
    return sFailures != 0;
}
